-- CreateTable
CREATE TABLE `ACCOUNT_INACTIVE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bar_code` VARCHAR(191) NOT NULL,
    `model` VARCHAR(191) NOT NULL,
    `balance` BIGINT NOT NULL DEFAULT 0,
    `status` VARCHAR(191) NOT NULL DEFAULT 'inactive',
    `ownerId` INTEGER NOT NULL,

    UNIQUE INDEX `ACCOUNT_INACTIVE_bar_code_key`(`bar_code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ACCOUNT_INACTIVE` ADD CONSTRAINT `ACCOUNT_INACTIVE_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `OWNER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
