-- CreateTable
CREATE TABLE `ADDRESS_TEMPORARY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `status` VARCHAR(191) NOT NULL,
    `ownerId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ADDRESS_TEMPORARY` ADD CONSTRAINT `ADDRESS_TEMPORARY_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `OWNER`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
